# mainatiner: nick.reva@snap.com
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|
#test for Yi!
  # set up root access
  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  NodeCount = 1

  # configure Kubernetes Nodes
  (1..NodeCount).each do |i|
    config.vm.define "node#{i}" do |node|
      # set base image for the vagrant box
      config.vm.box = "opensuse/Leap-15.2.x86_64"
      config.vm.box_version = "15.2.31.570"

      # set the static IP for the vagrant box
      node.vm.network "private_network", ip: "192.168.50.10#{i}"
      # configure the parameters for VirtualBox provider
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.memory = 2048
        v.cpus = 2
      end

    config.vm.provision "apparmor", type: "shell",
      inline: "sudo zypper --non-interactive install -t pattern apparmor"
    
    config.vm.provision "docker", type: "shell",
      inline: <<-SHELL
        sudo zypper --non-interactive install docker
        systemctl enable docker
        usermod -G docker -a $USER
        systemctl restart docker
      SHELL

    config.vm.provision "go", type: "shell",
      inline: <<-SHELL
        sudo zypper --non-interactive install git binutils bison gcc make
        sudo -u $USER -H bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
        sudo -u $USER -H bash -c 'echo "source $HOME/.gvm/scripts/gvm" >> $HOME/.bashrc'
        sudo -u $USER -H bash -c 'source $HOME/.gvm/scripts/gvm; gvm install go1.4 -B'
        sudo -u $USER -H bash -c 'source $HOME/.gvm/scripts/gvm; gvm install go1.17.2 -B'
        sudo -u $USER -H bash -c 'source $HOME/.gvm/scripts/gvm; gvm use go1.17.2 --default'
      SHELL
    end
  end
end
